### ISSUE TITLE
Ponoko Acrylic Case Parts and Asssembly

### ISSUE THREAD

**Issue by goranzarkovic** [coseyfannitutti/romeo#1]
Maybe I did something wrong but I have looked over the Readme and glanced at the renders for the custom acrylic case and I am not sure if maybe the parts needed count is slightly off.

It says 14x m2x5mm screws but around the border itself i think it needs 8 from the top and bottom (16) and then 3 more from the top and bottom of the feet (6), so 22 total.

Also, how does the PCB sit in the case? 
Is it sort of floating because the 3 holes on the bottom plate do not match up with holes on the PCB, and the pcb sort of currently rubs against the top screws, which i assume is resolved by soldering the plate mounted switches.

**Comment by coseyfannitutti** [comment]
Yes, the readme has been changed to reflect that difference in screw count.

The bottom plate from the kit and the screw holes on the pcb should not be used with the acrylic case. The PCB is held up by the plate included in this repository once switches are soldered.

**Comment by goranzarkovic** [comment]
Excellent thank you!
