### ISSUE TITLE
Acrylyc-Guard size?

### ISSUE THREAD

**Issue by lednax** [coseyfannitutti/romeo#2]
I've been looking through the repo but I can't find a reference to the size. Ponoko is not processing the size correctly. 

Can you include it in the README or somewhere else?

Thank you!

**Comment by lednax** [comment]
BUMP

**Comment by IOPNR** [comment]
> 
> 
> BUMP

Were you ever able to find the dimensions?

**Comment by dayofdoom** [comment]
I laser cut the acrylic guard in the repo today and it was the wrong size. If I had to guess, I think it's the mysterium's guard.

**Comment by coseyfannitutti** [comment]
@dayofdoom The way it was previously saved may have caused some potential scaling issues depending on what program it was opened with. I have changed the file to prevent that. Should be good now.

![image](https://user-images.githubusercontent.com/43188488/100569472-29a68d00-329c-11eb-84be-fc2a85a2bd71.png)
@lednax Sorry I didn't see this until now.
