### ISSUE TITLE
Acrylic guard bends easily, causing it to get poked by the header pins

### ISSUE THREAD

**Issue by kusamakura** [coseyfannitutti/romeo#3]
I appreciate the simplicity of four mounting points for the acrylic guard. But I have found that in normal use, such as picking up the keyboard, or holding the keyboard to support it when plugging a USB cable, the acrylic guard can hit the header pins, leaving permanent damage marks. I suppose this isn't a problem with the Discipline or the Mysterium because there are additional mounting points in the middle to support the guard; the Romeo, however, doesn't have this. I realize this is a very minor issue, but decided to let you know nonetheless, just in case. ;)

Anyway, great job on this board. It's a great first foray into the world of 40s.

**Comment by mabinin427** [comment]
Where did you find the dimensions to the acrylic guard?

**Comment by kusamakura** [comment]
> Where did you find the dimensions to the acrylic guard?

@mabinin427 I have the actual board.

But a quick look at the repo yields this: https://github.com/coseyfannitutti/romeo/blob/master/acrylic-guard.dxf

**Comment by mabinin427** [comment]
Oh okay. I guess I'll have to open that file then on my kicad. Since you have a romeo do you by any chance know why this does not seem to have a Gerber file for the plate other than what's provided for custom acrylic case?

**Comment by kusamakura** [comment]
> Since you have a romeo do you by any chance know why this does not seem to have a Gerber file for the plate other than what's provided for custom acrylic case?

Uh, I don't see how those are connected, but @coseyfannitutti simply forgot to add it? Sorry I can't help you much.
