### ISSUE TITLE
Plate for Romeo

### ISSUE THREAD

**Issue by IOPNR** [coseyfannitutti/romeo#4]
I'm having difficulty finding files for the Romeo plate. I saw that they were mentioned in the build guide but am not seeing it in the master files. Are the plate files available?

Edit: @coseyfannitutti Just wanted to follow up with this question in case you missed it. TIA Bryan!

**Comment by mabinin427** [comment]
I too am wondering why there isn't a Gerber file for the plate. Have you been able to find it?

**Comment by ymotongpoo** [comment]
ditto. It's great if you could add it onto the repository.

**Comment by coseyfannitutti** [comment]
I am working on a slight refresh for the romeo design that will include plate design. The repository will be updated with those files when it's done.
